#!/bin/bash

echo "apiVersion: v1"
echo "kind: Service"
echo "metadata:"
echo "  name: acme-challenge-service"
echo "  annotations:"
echo "    getambassador.io/config: |"
echo "      ---"
echo "      apiVersion: ambassador/v1"
echo "      kind:  Mapping"
echo "      name:  acme-challenge-mapping"
echo "      prefix: /.well-known/acme-challenge"
echo "      rewrite: \"\""
echo "      service: acme-challenge-service"
echo "spec:"
echo "  ports:"
echo "  - port: 80"
echo "    targetPort: 8089"
echo "  selector:"
echo "    certmanager.k8s.io/acme-http-domain: $1"
echo "    certmanager.k8s.io/acme-http-token: $2"
