apiVersion: v1
kind: Service
metadata:
  name: bitcoin-abc
  labels:
    name: bitcoin-abc
spec:
  ports:
  - port: 8332
    targetPort: 8332
    name: rpc
  - port: 28332
    targetPort: 28332
    name: zmq
  clusterIP: None
  selector:
    app: bitcoin-abc
