apiVersion: v1
kind: Service
metadata:
  name: litecoin
  labels:
    name: litecoin
spec:
  ports:
  - port: 9332
    targetPort: 9332
    name: rpc
  - port: 28332
    targetPort: 28332
    name: zmq
  clusterIP: None
  selector:
    app: litecoin
