apiVersion: v1
kind: Service
metadata:
  name: ltc-explorer-api
  labels:
    app: ltc-explorer-api
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  ltc-explorer-api_mapping
      prefix: /api/explorer/ltc/
      rewrite: /
      service: ltc-explorer-api:80
      use_websocket: true
      cors:
        origins: "*"
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: ltc-explorer-api
  type: ClusterIP
