apiVersion: v1
kind: Service
metadata:
  name: ltc-explorer-ui
  labels:
    app: ltc-explorer-ui
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  ltc-explorer-ui_mapping
      prefix: /explorer/ltc/
      rewrite: /
      service: ltc-explorer-ui:80

spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: ltc-explorer-ui
  type: ClusterIP
