apiVersion: v1
kind: Service
metadata:
  name: wallet-service-messenger
  labels:
    app: wallet-service-messenger
spec:
  ports:
  - name: port-1
    port: 3380
    protocol: TCP
    targetPort: 3380
  selector:
    app: wallet-service-messenger
  type: ClusterIP
