apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
spec:
  serviceName: "litecoin"
  selector:
    matchLabels:
      app: litecoin
  replicas: 1
  template:
    metadata:
      labels:
        app: litecoin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: registry.hub.docker.com/owstack/litecoin:0.16.3.0-ows
        name: litecoin
        command: ["litecoind"]
        args: ["-addresstype=p2sh-segwit", "-datadir=/data", "-server=1", "-addressindex=1", "-spentindex=1", "-timestampindex=1", "-txindex=1", "-zmqpubrawtx=tcp://0.0.0.0:28332", "-zmqpubhashblock=tcp://0.0.0.0:28332", "-rpcallowip=0.0.0.0/0", "-rpcuser=$(RPCUSERNAME)", "-rpcpassword=$(RPCPASSWORD)", "-dbcache=512", "-rpcthreads=32", "-rest=1", "-printtoconsole"]
        ports:
        - containerPort: 9332
        - containerPort: 9333
        - containerPort: 28332
        env:
        - name: RPCUSERNAME
          valueFrom:
            secretKeyRef:
              name: rpcsecret
              key: username
        - name: RPCPASSWORD
          valueFrom:
            secretKeyRef:
              name: rpcsecret
              key: password
        volumeMounts:
        - mountPath: /data
          name: litecoin-persistent-storage
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: litecoin-persistent-storage
    spec:
      storageClassName: ssd
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 100Gi
