apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service-notify-push
  labels:
    app: wallet-service-notify-push
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-service-notify-push
  template:
    metadata:
      labels:
        app: wallet-service-notify-push
    spec:
      containers:
      - image: registry.hub.docker.com/owstack/wallet-service:v0.2.8
        name: wallet-service-notify-push
        command: ["node", "base-service/ws.js"]
        env:
        - name: DB_CONN_STRING
          value: mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/wallet-service?replicaSet=rs0
        - name: MESSAGE_BROKER_URL
          value: http://wallet-service-messenger:3380
        - name: LOCKER_SERVER_NAME
          value: wallet-service-locker
        - name: EMAIL_EXPLORER_URL_TEMPLATE
          value: https://dev.owstack.org/explorer/{{currency}}/tx/{{txid}}
        - name: GOOGLE_FCM_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: fcmkey
              key: fcmkey
